### ISSUE TITLE
If you disconnect while spectating someone, you login at the backup location in spectate gamemode.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#10]
**Describe the bug**
Player gamemode isn't reverted back / set to survival on login if disconnecting from inside the game.

**To Reproduce**
1. Player 1 joins WITP.
2. Player 2 joins WITP.
3. Player 1 changes gamemode to spectate Player 2 using WITP options menu.
4. Player 1 disconnects.
5. Player 1 rejoins.
6. Player 1 gets a message saying ``You have been teleported to a backup location`` but is still in the spectate gamemode.
**Screenshots**

**Errors**
None.

**Versions**
- WalkInThePark v2.0
- Paper dev 467 (Spigot 1.16.5)

**Additional context**
```
# Options for the world
world:
    # The world in which the personal parkours will take place
    name: witp

    # The world players will be teleported to if they accidentally join the WITP world without being a player
    fall-back: spawn
```
