### ISSUE TITLE
Left message does not occur when you use the quit option from the GUI.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#21]
Compiled as of commit https://github.com/Efnilite/Walk-in-the-Park/commit/2f21af98ebc02d0df37b80ae981382070c839566

If you open the GUI and click ``Quit``, the ``left`` language string message does not occur. It only seems to appear when you manually type ``/parkour leave``.

```
    en:
        join: '&7%p has joined the server'
        leave: '&7%p has left the server'
        joined: '&a&l(!) &7You joined the parkour'
        left: '&c&l(!) &7You left the parkour'
```
