### ISSUE TITLE
focus-mode is not denying all commands not whitelisted

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#28]
Despite focus-mode being forced on, players are able to use the command ``/spawn`` to leave the parkour map. Either focus-mode is not properly blocking all commands _or_ because I use ``spawn`` as a fall-back world / go-back configuration, it's breaking WITP.

```
# Options for focus mode.
focus-mode:

    # If focus mode is enabled players can't use commands while in parkour.
    enabled: true

    # A whitelist for commands which ARE allowed during focus mode (if focus mode is enabled).
    # If you want to disable the default whitelisted commands you can remove every item in the list below.
    whitelist:
    - 'witp'
    - 'parkour'
    - 'msg'
    - 'r'
    - 'w'
    - 'whisper'
    - 'reply'
    - 'message'
    - 'tell'
    - 'me'
    - 'ac'
    - 'musicbox'
    - 'money'
    - 'bal'
    - 'balance'
```

```
    # If go back is enabled
    go-back-enabled: false

    # The place players will go back to if they leave, if bungeecord is disabled and the go-back option is enabled
    # You need to retain this format, or else it won't work: '(x,y,z,world)'
    go-back: (9,58,0,spawn)
```
```
# Options for the world
world:
    # The world in which the personal parkours will take place
    name: witp

    # The world players will be teleported to if they accidentally join the WITP world without being a player
    fall-back: spawn
```
