### ISSUE TITLE
WITP ticking entities despite having no mob spawns.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#57]
WITP compiled as of commit https://github.com/Efnilite/Walk-in-the-Park/commit/799e054dfe832ab3e851ea78b98da4ac6880b799

Ran a timings profiler for 3 minutes just out of curiosity. Saw the witp world doing a tickEntities task for some reason when no players were in the world.

![link](https://i.imgur.com/IpLHAsW.png)

No entities were in the world either. Just the initial spawn chunks.
![l2](https://i.imgur.com/58jcK9f.png)

I assume a fix would be to set ``witp`` world's multiverse settings for ``spawning`` animals & monsters to false.
```
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'false'
        spawnrate: '-1'
        exceptions: []
```

As well as disabling the ``keepSpawnInMemory`` since WITP doesn't have a global player spawn location. No point in keeping chunks loaded and ticking.

``keepSpawnInMemory: 'false'``

I cannot make these changes as witp deletes the configuration in multiverse when it resets the world and regenerates it.
