### ISSUE TITLE
Joined/Left messages are missing from new messages v3 file.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#73]
**Describe the bug**

The joined and left player messages are missing from the new messages file.

```
messages:
    # English (English)
  en:
    joined: '&a&l(!) &7You joined the parkour'
    left: '&c&l(!) &7You left the parkour'
```

**To Reproduce**
1. Delete WITP folder.
2. Generate new.
3. Inspect new messages-v3.yml file.

**Versions**
- v3.0.1 - Hotfix

**Additional context**
I used these messages to notify the player when they themselves have joined or left parkour. They seem to be missing in the new messages list now.
